---
- name: Install PlantUML on Manjaro
  hosts: all
  become: yes
  vars:
    user_home: "/home/{{ ansible_env.SUDO_USER }}"

  tasks:
    - name: Update the pacman package database
      pacman:
        update_cache: yes

    - name: Install Graphviz (required by PlantUML)
      pacman:
        name: graphviz
        state: present

    - name: Ensure the destination directory exists
      file:
        path: "{{ user_home }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_env.SUDO_USER }}"
        group: "{{ ansible_env.SUDO_USER }}"

    - name: Download PlantUML jar file as the non-root user
      become: no
      get_url:
        url: "https://github.com/plantuml/plantuml/releases/download/v1.2024.6/plantuml.jar"
        dest: "{{ user_home }}/plantuml.jar"
        mode: '0755'
